### ISSUE TITLE
Muting other spectators does not work

### ISSUE THREAD

**Issue by ElTyranos** [IDI-Systems/acre2#372]
**Arma 3 Version:** `1.71`
**CBA Version:** `3.3.1.170504`
**ACRE2 Version:** `2.4.2.962`

**Mods:**
-mod=@CBA_A3;@CUP_Terrains_Core;@BG21_Core;@BG21_IF;@ace;@FOW;@IFA3_AIO_LITE;@acre2;

**Description:**
- Muting other spectators does not work.

**Steps to reproduce:**
- Get in PvP
- Die, moved to spectator (with onPlayerKilled.sqf >` [true] call acre_api_fnc_setSpectator`)
- press the "mute spectator" shortcut
- Nothing happens and other spectator keep yelling

**Where did the issue occur?** Dedicated

**Placed Modules:** None of ACRE. ACRE enabled via init.sqf > `[true, true] call acre_api_fnc_setupMission;`

**RPT log file:** https://paste.ubuntu.com/24799931/

NB : 
BG21_Core = Bloodsplatter Lite ;L_MOUNT ; SAN_Headlamps ; Zade_boc ;
BG21_IF = WMT mission framework + compatibility files (IF/ACE/FOW)
https://github.com/iEzhuk/WMT_MapTools

**Comment by Sniperhid** [comment]
`press the "mute spectator" shortcut` This sounds like an issue with the spectator system you are using? It's probably blocking the keybind from going through.

Which spectator system are you using?

**Comment by jonpas** [comment]
Is that mute spectator a function of spectator you are using? Vanilla or ACE3?

**Comment by ElTyranos** [comment]
![image](https://user-images.githubusercontent.com/6755711/26877091-164108f6-4b89-11e7-93a3-000e1f9fd455.png)

Indeed @Sniperhid that's the mute spectator shortcut. Unless I did not understand how it works.

We use vanilla spectator mode. Check out https://github.com/ElTyranos/BG21_PvP/blob/master/onPlayerKilled.sqf

**Comment by ElTyranos** [comment]
https://github.com/CBATeam/CBA_A3/pull/694
https://github.com/CBATeam/CBA_A3/issues/692

Could be related to these ?

**Comment by jonpas** [comment]
Maybe vanilla spectator doesn't pass keybinds through since it got reworked.

**Comment by ElTyranos** [comment]
adding 

```
	[] spawn
	{
		findDisplay 60492 displayAddEventHandler ["KeyDown",
			{
				if (((_this select 1) == 62) && (!dialog)) then
				{
				   [] call acre_sys_core_fnc_toggleHeadset;
				};
				false
			}
		];
	};

```
to onplayerkilled.sqf fixes the issue (assigns a new key)

**Comment by jonpas** [comment]
What is that display 60492? Vanilla spectator?

**Comment by ElTyranos** [comment]
Yup

**Comment by jonpas** [comment]
```cpp
class Extended_DisplayLoad_EventHandlers {
    class RscDisplayEGSpectator {
        ADDON = QUOTE(_this call COMPILE_FILE(XEH_spectatorEGDisplayLoad));
    };
};
```
```sqf
params ["_display"];

_display displayAddEventHandler ["KeyDown", {_this call FUNC(handleKeyDown)}];
```
```sqf
params ["", "_key", "_shift", "_ctrl", "_alt"];

if ([_key, [_shift, _ctrl, _alt]] in ((["ACRE2", "HeadSet"] call CBA_fnc_getKeybind) select 8)) then {
    [] call acre_sys_core_fnc_toggleHeadset;
};

false
```

This should solve it for vanilla spectator, and we can make it an API function so modded spectators can also call it if they block keys for some reason. Will PR later/tomorrow.

I am assuming this doesn't happen with ACE3 spectator?

**Comment by VyMajoris** [comment]
It seems that this is still an issue. Now pressing the key to to toggle spectators makes triggers two events, one immediately followed by another, muting and unmuting it.

![image](https://user-images.githubusercontent.com/4342296/71327007-9b4d5700-24e1-11ea-821c-940218575141.png)

**Comment by jonpas** [comment]
Please make a new issue with all the information in the template. Also include which spectator system you are using and any modifications if you have them.
